version: "3.8"

services:
  db:
    image: postgres:15
    container_name: task-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: task-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/taskdb"
      JWT_SECRET: "your_secret_key"
      PORT: 5000
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: task-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
